// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog/blog.proto

package go_micro_srv_blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CreateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{3}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.blog.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.blog.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.blog.Response")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.blog.CreateRequest")
}

func init() { proto.RegisterFile("proto/blog/blog.proto", fileDescriptor_e6e11f767506fb4e) }

var fileDescriptor_e6e11f767506fb4e = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcf, 0x4a, 0xc4, 0x40,
	0x0c, 0xc6, 0xed, 0x1f, 0x5b, 0x0d, 0x28, 0x1a, 0x54, 0xca, 0xae, 0xc2, 0x32, 0x27, 0x4f, 0x23,
	0xe8, 0x0b, 0x88, 0x1e, 0xc4, 0x83, 0x97, 0xbe, 0xc1, 0xec, 0x6e, 0x18, 0x0b, 0x6d, 0x67, 0x9d,
	0x64, 0x05, 0x9f, 0xc3, 0x17, 0x96, 0x4d, 0xdb, 0x83, 0xb8, 0xe0, 0x65, 0xc8, 0x37, 0xbf, 0x7c,
	0x21, 0x5f, 0xe0, 0x72, 0x13, 0x83, 0x84, 0xbb, 0x65, 0x1b, 0xbc, 0x3e, 0x56, 0x35, 0x9e, 0xfb,
	0x60, 0xbb, 0x66, 0x15, 0x83, 0xe5, 0xf8, 0x69, 0x77, 0xc0, 0xcc, 0xa1, 0x7c, 0x23, 0x66, 0xe7,
	0x09, 0xcf, 0x20, 0x63, 0xf7, 0x55, 0x25, 0x8b, 0xe4, 0xf6, 0xb8, 0xde, 0x95, 0xe6, 0x06, 0xca,
	0x9a, 0x3e, 0xb6, 0xc4, 0x82, 0x08, 0x79, 0xef, 0x3a, 0x1a, 0xa9, 0xd6, 0xe6, 0x1a, 0x8e, 0x6a,
	0xe2, 0x4d, 0xe8, 0x59, 0xcd, 0x1d, 0xfb, 0xc9, 0xdc, 0xb1, 0x37, 0x1e, 0x4e, 0x9e, 0x23, 0x39,
	0xa1, 0x69, 0xc4, 0x29, 0xa4, 0xcd, 0x5a, 0x3b, 0xb2, 0x3a, 0x6d, 0xd6, 0x78, 0x01, 0x87, 0xd2,
	0x48, 0x4b, 0x55, 0xaa, 0xa6, 0x41, 0x60, 0x05, 0xe5, 0x2a, 0xf4, 0x42, 0xbd, 0x54, 0x99, 0xfe,
	0x4f, 0x12, 0xaf, 0xa0, 0x70, 0x5b, 0x79, 0x0f, 0xb1, 0xca, 0x15, 0x8c, 0xea, 0xfe, 0x3b, 0x81,
	0xfc, 0xa9, 0x0d, 0x1e, 0x1f, 0x21, 0x7b, 0x21, 0xc1, 0x99, 0xfd, 0x13, 0xd3, 0x8e, 0x3b, 0xcc,
	0xe6, 0x7b, 0xd9, 0x90, 0xc1, 0x1c, 0xe0, 0x2b, 0x14, 0xc3, 0xce, 0xb8, 0xd8, 0xd3, 0xf8, 0x2b,
	0xce, 0x3f, 0xa3, 0x96, 0x85, 0x9e, 0xfc, 0xe1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x18, 0x82,
	0xa8, 0x8b, 0x01, 0x00, 0x00,
}
