// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/blog/blog.proto

package go_micro_srv_blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Blog service

type BlogService interface {
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*Response, error)
}

type blogService struct {
	c    client.Client
	name string
}

func NewBlogService(name string, c client.Client) BlogService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.blog"
	}
	return &blogService{
		c:    c,
		name: name,
	}
}

func (c *blogService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Blog.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Blog.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Blog service

type BlogHandler interface {
	Get(context.Context, *Request, *Response) error
	Create(context.Context, *CreateRequest, *Response) error
}

func RegisterBlogHandler(s server.Server, hdlr BlogHandler, opts ...server.HandlerOption) error {
	type blog interface {
		Get(ctx context.Context, in *Request, out *Response) error
		Create(ctx context.Context, in *CreateRequest, out *Response) error
	}
	type Blog struct {
		blog
	}
	h := &blogHandler{hdlr}
	return s.Handle(s.NewHandler(&Blog{h}, opts...))
}

type blogHandler struct {
	BlogHandler
}

func (h *blogHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.BlogHandler.Get(ctx, in, out)
}

func (h *blogHandler) Create(ctx context.Context, in *CreateRequest, out *Response) error {
	return h.BlogHandler.Create(ctx, in, out)
}
